src/components/atoms/input/Index.module.scss, src/components/atoms/input/index.tsx
Componente input con funcionalidad de button opcional y dos diferentes tamaños. 
#42
=> add-input-component

package-lock.json, src/hooks/useLocalStorage.tsx
- useLocalStorage Hook added for user session manage
=> feat: useLocalStorage hook added for user session manage

.eslintrc.js, package-lock.json, package.json, src/components/atoms/file.txt, src/components/molecules/Slider/Slider.module.scss, src/components/molecules/Slider/index.tsx, src/pages/HomePage.tsx
=> React range slider

package-lock.json, package.json, src/components/atoms/Modal/Modal.module.scss, src/components/atoms/Modal/index.tsx, src/pages/HomePage.tsx
Modal atom, ejemplo de uso:
#44
=> Modal atom

src/components/atoms/CategoryInput/CategoryInput.module.scss, src/components/atoms/CategoryInput/index.tsx, src/components/molecules/Header/Header.module.scss, src/components/molecules/Header/index.tsx, src/components/templates/Layout/Layout.module.scss, src/components/templates/Layout/index.tsx, src/hooks/useForm.tsx, src/pages/BoardPage.tsx, src/routes.ts
category input atom y board screen, falta letra actual en el header
#48
=> category input atom and board screen

src/contexts/RoomContextState.tsx, src/firebase/services/room.ts, src/main.tsx, src/pages/HomePage.tsx, src/types/room.ts
Se crea el contexto para Room, solo es un approach de base para avanzar, en el contexto se esta asignando un roomKey existente en firebase, tiene un test en HomePage.tsx, falta mucha implementacion aun pero creo que tiene la estructura.
=> feat: RoomContext added

src/contexts/RoomContextState.tsx, src/firebase/services/room.ts
Envio informacion del contexto local de partida a firebase para que haya una sincronizacion de ida y vuelta
=> Envio informacion del contexto local a firebase

src/contexts/PlayerContextState.tsx, src/firebase/services/players.ts, src/main.tsx
Player Context added, online status check added
Se puede ver como su status online cambia a false cuando se cierra el navegador o refresca la pagina.
=> feat: player context added, online status listening

src/components/Organisms/Rooms/index.tsx, src/contexts/PlayerContextState.tsx, src/firebase/services/players.ts, src/pages/BoardPage.tsx, src/types/room.ts
=> feat: board integration

package.json, src/contexts/PlayerContextState.tsx, src/contexts/RoomContextState.tsx, src/firebase/services/room.ts, src/pages/BoardPage.tsx, src/types/room.ts
Se guarda los answers de los players desde Board al presionar el boton de STOP!
=> feat: saving players answers in DB

src/scss/colors.scss, src/scss/fonts.scss, src/scss/typography-movile.scss
Variables principales del style-guide
#13
=> add fundamental variables

src/components/atoms/Countdown/Countdown.module.scss, src/components/atoms/Countdown/index.tsx, src/components/atoms/Letter/Letter.module.scss, src/components/atoms/Letter/index.tsx, src/components/atoms/homescreen/assets/index.scss, src/components/molecules/PlayersList/index.tsx, src/components/molecules/PreviewInfoRoom/index.tsx, src/contexts/RoomContextState.tsx, src/pages/BoardPage.tsx, src/pages/NewGame/index.tsx, src/pages/PreviewPage.tsx, src/pages/RoomsPage/index.tsx, src/pages/ValidationPage/index.tsx, src/routes.ts, src/types/room.ts
- Link preview and board pages
- Generar link para invitar amigos
- Crear una nueva roundGame
- Setear la letra
- Mostrar componentes letter and countdown
=> Link preview and board pages

src/firebase/services/room.ts, src/pages/NewGame/index.tsx, src/pages/ValidationPage/index.tsx
se obtiene un contandor de la DB , y se agrega la propiedad name a la hora de crear una room
=> feat: se agrega name a la room

src/components/atoms/Avatars/index.tsx, src/components/atoms/homescreen/index.tsx, src/contexts/PlayerContextState.tsx, src/pages/ValidationPage/index.tsx, src/types/room.ts
Se agrega integracion de usuario de home
=> feat: integration user from home

package.json, src/components/Organisms/Rooms/index.tsx, src/components/molecules/PreviewInfoRoom/index.tsx, src/contexts/RoomContextState.tsx, src/hooks/useRoomState/index.tsx, src/hooks/useRoomState/types.ts, src/pages/EditGame/constants.ts, src/pages/NewGame/constants.ts, src/pages/PreviewPage.tsx, src/routes.ts, src/types/room.ts
- Empiezo a integrar los estados en la partida
- Agrego `isLastRound`, `isHost` y `alreadyInTheGame` en el contexto de la partida
- Integro la pagina de preview y hago redirecciones hacia el board
Es solo para ir mergeando los prs de a poco, me gustaria probarlo arriba, por eso armo el pr con esta primer parte cerrada, pero faltan las demas vistas
https://watch.screencastify.com/v/ycRkd52Hjklc4LEb93Gj
=> Agrego punto de partida para el manejo de estados

src/components/Organisms/EditCategories/constants.ts, src/components/atoms/Letter/index.tsx, src/components/molecules/PreviewInfoRoom/index.tsx, src/firebase/services/roundsGame.ts, src/hooks/useRoomState/index.tsx, src/hooks/useRoomState/types.ts, src/pages/BoardPage.tsx, src/pages/EditGame/constants.ts, src/pages/NewGame/constants.ts, src/pages/NewGame/index.tsx, src/pages/PreviewPage.tsx
guardo las respuestas del tablero en una nueva coleccion llamada "roundGame"
Integro en cambio de estados en la pantalla del tablero
Agrego que el jugador que crea la partida sea el host
=> Agrego control de estado para la pagina del tablero

src/components/Organisms/Validation/WordsValidation/index.tsx, src/contexts/RoomContextState.tsx, src/firebase/services/roundsGame.ts, src/pages/ValidationPage/index.tsx, src/types/room.ts
Agrego integracion de estados y trancision en la pantalla de validation
=> Room state validation

src/components/molecules/PreviewInfoRoom/index.tsx, src/pages/PreviewPage.tsx
Pequeños arreglos tipográficos en el preview y en el modal.
#117
=> minimal changes on previewpage

src/assets/bgGold.svg, src/components/atoms/Avatars/assets/index.scss, src/components/atoms/Avatars/index.tsx, src/components/molecules/ClassificationCard/ClassificationCard.module.scss, src/components/molecules/ClassificationCard/index.tsx, src/components/molecules/Winner/Winner.module.scss, src/components/molecules/Winner/index.tsx, src/components/templates/Layout/Layout.module.scss, src/components/templates/Layout/index.tsx, src/pages/ProvisionalClasPage.tsx
Muestro los jugadores de la partida en la pantalla de clasificacion
// TODO: 
Agregar puntajes a los jugadores
El header se soluciona con el issue #137 
Final:
Provisional:
=> Clasification

src/components/molecules/Header/Header.module.scss, src/components/molecules/Header/index.tsx, src/components/templates/Layout/Layout.module.scss, src/components/templates/Layout/index.tsx
Corrección de pequeños bugs visuales por parte del header en diferentes implementaciones y se le agregó fixed al position.
#137
=> fix layout bug & implement position fixed

src/pages/AboutPage.tsx, src/pages/styles/aboutPages.module.scss
use of Layout component in component about us. Small style changes
#50
=> use of Layout component in component about us. Small style changes
